### ISSUE TITLE
Three themes that are not included on the Rose Pine site

### ISSUE THREAD

**Issue by wahyuwiyoko** [rose-pine/rose-pine-site#118]
These three themes are available on Rose Pine repository but not included on the [site](https://rosepinetheme.com/themes/).

- [Xresources](https://github.com/rose-pine/xresources)
- [Mona](https://github.com/rose-pine/mona)
- [Hyprland](https://github.com/rose-pine/hyprland)

Maybe the site are not updated yet? Or did I miss one of those on the site?

**Comment by mvllow** [comment]
Thanks for letting us know! Updated :)
