### ISSUE TITLE
Weird looking language selection icon

### ISSUE THREAD

**Issue by yheuhtozr** [rose-pine/rose-pine-site#129]
I guess the language selection icon on the top right side is hand-crafted, imitating the common one symbolizing 文 and A. However, the (alleged) Chinese character on the icon instead looks exactly like 丈 (which means: "fathom (a unit of average human height)", "size", "measurement") that makes the meaning of the icon confusing to whoever reads the character. Based on the overall style, I recommend that it should be changed somewhat like below.

|current|suggested|
|:-:|:-:|
|![Screen Shot 2023-12-29 at 01 39 28](https://github.com/rose-pine/rose-pine-site/assets/84892012/4a6189aa-8c7e-40e9-9250-cb6ccea8bbdc)|![suggested_icon](https://github.com/rose-pine/rose-pine-site/assets/84892012/015d3f5d-78c6-409d-a0c5-ca86469a0634)|

**Comment by fvrests** [comment]
Thanks for catching that. Looks like the icon set used in the site has an outstanding issue to fix the icon: [tabler/tabler-icons #416](https://github.com/tabler/tabler-icons/issues/416). I tweaked the icon to hopefully look more like the correct character in the style of the icon set. Please feel free to let us know if it's still not quite right or there are any other issues. :)

**Comment by yheuhtozr** [comment]
Thank you, I didn't know that the icon is taken from an existing set. Now it looks great to me.
