### ISSUE TITLE
rose-pine-man theme

### ISSUE THREAD

**Issue by const-void** [rose-pine/rose-pine-site#149]
Hello all, fell in love the rose-pine theme. Created a rose-pine (terminal) theme for man pages which might plug a gap.

https://github.com/const-void/rose-pine-man

wasn't sure what I had to do to submit for ez-access from the rose garden!

thank you all.

**Comment by mvllow** [comment]
Thanks for sharing! I'd suggest looking at this recent PR: https://github.com/rose-pine/rose-pine-site/pull/148/files

Simply add an entry (in alphabetical order) to the community-repos.json :)

**Comment by const-void** [comment]
ty, will do!
