### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by andreasgrafen** [rose-pine/rose-pine-site#15]
Cheers!
I've stumbled across **Rosé Pine** while doing research for some other stuff, and I gotta say: **I'm in love**! ♡

I've noticed that there are different locales available for your website and I was thinking if there would be a need for a translation into German? I'd love to contribute that, but also don't wanna do the work just to make a PR you guys aren't actually looking for. Let me know what you think, and if you'd like me to get to work on this. ^—^

**Comment by mvllow** [comment]
That would lovely! Let me know if you have any questions as far as implementing a new locale 🥰

**Comment by andreasgrafen** [comment]
I've just been looking through the code – trying to get an idea of what actually needs changing to get a new locale set up. I wanna say that I have a somewhat clear idea of what to do; If anything comes up I'll make sure to reach out tho. c:

**Comment by andreasgrafen** [comment]
Okay, I think I've got it right? at least the automatically generated preview — which I was really confused about btw — looks alright. The main Title is a little annoying as »Etwas Wunderschönes« doesn't get broken down – tho it could be »Wunder- `\n` schönes«. But it's probably not possible to do that?

**Comment by mvllow** [comment]
Oh that's a good idea. I'll try to add a break in there 😌 Thank you!

**Comment by andreasgrafen** [comment]
It's still a little awkward, but def. looks a lot better imo. c:

![Screenshot from 2022-01-29 23-35-13](https://user-images.githubusercontent.com/35840154/151679754-1fa9a76d-673f-4e94-9763-9f4f04f58639.png)

**Comment by mvllow** [comment]
Just pushed an update that should allow it to break like your screenshot 😌

**Comment by andreasgrafen** [comment]
Works like a charm without devtool magic now. ♡
