### ISSUE TITLE
[Feature Request] Palette Usage

### ISSUE THREAD

**Issue by ng-hai** [rose-pine/rose-pine-site#19]
I'm building new website using Rose Pine palette, and I think it would be super helpful if there is an instruction or a note about how to apply specific color in some context.

### Example
|Color|Hex|Note|
|--|--|--|
|base|#191724|Usually apply for background (`<body>`)|
|surface|#1f1d2e|Background color but for card, or button|

**Comment by mvllow** [comment]
This is on our list of things to add – for the time being this an unorganised, work in progress spec:

## Interface

**base**

Primary background. Eg. inactive tabs, sidebars

**surface**

Low contrast background, used atop `base`. Eg. text inputs, panels

**overlay**

Medium contrast background, used atop `surface`. Eg. text inputs, panels, active tabs

**muted**

Low contrast foreground. Eg. gitignored files in a sidebar

**subtle**

Medium contrast foreground. Eg. inactive tabs, non-selected results

**text**

High contrast foreground. Eg. active tabs, selected results, selection foreground (paired with **highlight med** background)

**highlight low**

cursor line

**highlight med**

selection background (paired with **text** foreground)

**highlight high**

search matches

## Syntax

**muted**

comments

**subtle**

punctuation, symbols

**text**

variables

**love**

builtins

**gold**

strings

**rose**

booleans

**pine**

functions

**foam**

keys

**iris**

parameters, links

**Comment by ng-hai** [comment]
Have a look at my demo 😄 
https://hari.work

**Comment by ng-hai** [comment]
Should I sacrifice contrast ratio for not giving an eye strain to the reader?

My current styling for article, I use `text` for heading and `subtle` for body.
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/19520278/169530443-89303459-f462-42ae-b899-86f6514e21fd.png">

And this is what Lighthouse recommend me
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/19520278/169530539-e7ecdd35-8d12-4b4d-a73e-e81745722b0a.png">

**Comment by mvllow** [comment]
Are you using `#908caa` for subtle? We bumped up the contrast a while back and our old subtle colour is now "muted"

**Comment by ng-hai** [comment]
Yes I use the palette on https://rosepinetheme.com/palette
