### ISSUE TITLE
Add GDevelop theme

### ISSUE THREAD

**Issue by EhanAhamed** [rose-pine/rose-pine-site#70]
### Link to theme repo

https://github.com/rose-pine/GDevelop

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

I realize I should have made an issue before creating a new repo... oops 🤷

See [this pull request](https://github.com/4ian/GDevelop/pull/4079) in [GDevelop's repo](https://github.com/4ian/GDevelop/) for more info!

**Comment by mvllow** [comment]
Transferred to track adding this theme to the website

**Comment by EhanAhamed** [comment]
Great! I'll add the theme to the list right now! 🤩🤩

**Comment by EhanAhamed** [comment]
I've opened a pull request to add it to the list! 😄😄

See #71
