### ISSUE TITLE
Improve internationalisation experience

### ISSUE THREAD

**Issue by mvllow** [rose-pine/rose-pine-site#78]
**The problems**

1. There is no way via the interface to change locales without javascript
2. The default locale content flashes before loading the desired locale, even when default == desired

**The potential solutions**

Ideally, we would be able to use path-based locale routing, e.g. `rosepinetheme.com/it/` or `rosepinetheme.com/en/palette`. This would remove the need for javascript to switch locales.

The above changes may make it easier to statically generate translations at build time, solving any content flickers.

**Comment by khaki32** [comment]
There's an [open issue](https://github.com/sveltejs/kit/issues/553) for this on the SvelteKit repository.

**Comment by mvllow** [comment]
Ooh interesting, would love to see a solution builtin to SvelteKit. That thread has lots of good options until then, too! Thanks :)
